### ISSUE TITLE
Refactor convoluted hardcoded projects

### ISSUE THREAD

**Issue by Uzay-G** [NilsIrl/www.nilsand.re#2]
Here https://github.com/NilsIrl/www.nilsand.re/blob/65b2aac77599e44581deddd20396d204ec116a2e/index.html#L14-L25, you have hard-coded the projects into your html.

Instead you could create a markdown collection in jekyll that would be a more elegant and efficient way of organising the structure of the website.

You could take this as an example: https://github.com/Uzay-G/portfolio/tree/master/_projects

**Comment by NilsIrl** [comment]
This is not more efficient and there is no need to reuse this information. This is why it is placed there.
